Repository InseeFrLab/cartiflette, pull requests merged in 2022-10, with the labels that each got.

#19 Packagisation des scripts
  cartiflette/download/__init__.py
  cartiflette/download/dev.py
  cartiflette/s3/__init__.py
  cartiflette/s3/s3.py
  cartiflette/utils/__init__.py
  cartiflette/utils/_download_pb.py
  cartiflette/utils/_import_yaml_config.py
  cartiflette/utils/dict_correspondance.py
  cartiflette/utils/keep_subset_geopandas.py
  cartiflette/utils/sources.yaml
  pyproject.toml
  s3.py
  setup.py
Labels: package :package:

#20 Continuous integration setup for package
  .github/workflows/python-package-conda.yml
  cartiflette/__init__.py
Labels: Continuous integration

#25 maj sources.yaml - ajout divers zonages d'études
  cartiflette/utils/sources.yaml
Labels: catalogue des sources

#26 Multiple downloads
  cartiflette/s3/__init__.py
  cartiflette/s3/s3.py
  misc/write_s3.py
Labels: s3

#29 Download via des liens
  README.md
  cartiflette/s3/__init__.py
  cartiflette/s3/s3.py
  example/download.py
Labels: s3
